export type CryptosuiteErrorCode =
  | 'BASE64URL_INVALID'
  | 'CRYPTO_UNAVAILABLE'
  | 'SUBTLE_UNAVAILABLE'
  | 'GET_RANDOM_VALUES_UNAVAILABLE'
  | 'AES_GCM_UNSUPPORTED'
  | 'HMAC_SHA256_UNSUPPORTED'
  | 'RSA_OAEP_UNSUPPORTED'
  | 'ED25519_UNSUPPORTED'
  | 'SHA256_UNSUPPORTED'
  | 'BUFFER_SOURCE_EXPECTED'
  | 'AES_GCM_KEY_EXPECTED'
  | 'AES_GCM_ALG_INVALID'
  | 'AES_GCM_KEY_SIZE_INVALID'
  | 'AES_GCM_KEY_OPS_INVALID'
  | 'AES_GCM_USE_INVALID'
  | 'AES_GCM_RAW_LENGTH_INVALID'
  | 'AES_GCM_IV_LENGTH_INVALID'
  | 'HMAC_KEY_EXPECTED'
  | 'HMAC_ALG_INVALID'
  | 'HMAC_KEY_SIZE_INVALID'
  | 'HMAC_KEY_OPS_INVALID'
  | 'HMAC_USE_INVALID'
  | 'HMAC_RAW_LENGTH_INVALID'
  | 'RSA_OAEP_PUBLIC_KEY_EXPECTED'
  | 'RSA_OAEP_PRIVATE_KEY_EXPECTED'
  | 'RSA_OAEP_ALG_INVALID'
  | 'RSA_OAEP_MODULUS_LENGTH_INVALID'
  | 'RSA_OAEP_EXPONENT_INVALID'
  | 'RSA_OAEP_KEY_OPS_INVALID'
  | 'RSA_OAEP_USE_INVALID'
  | 'ED25519_PUBLIC_KEY_EXPECTED'
  | 'ED25519_PRIVATE_KEY_EXPECTED'
  | 'ED25519_CURVE_INVALID'
  | 'ED25519_ALG_INVALID'
  | 'ED25519_KEY_SIZE_INVALID'
  | 'ED25519_KEY_OPS_INVALID'
  | 'ED25519_USE_INVALID'

export class CryptosuiteError extends Error {
  readonly code: CryptosuiteErrorCode

  constructor(code: CryptosuiteErrorCode, message?: string) {
    const detail = message ?? code
    super(`{@z-base/cryptosuite} ${detail}`)
    this.code = code
    this.name = 'CryptosuiteError'
  }
}
